# Gaming Player Retention & Engagement Analytics Platform

### Python | MySQL | SQL | Power BI | Retention Analytics | Cohort Analysis

## Project Overview

This project analyzes player registration and login activity data to measure player growth, engagement, and retention.

Key metrics analyzed include:

- Daily Active Users (DAU)
- Monthly Active Users (MAU)
- New Player Registrations
- Peak DAU
- Day 1 Retention
- Day 7 Retention
- Day 30 Retention
- Cohort Analysis

The project follows an end-to-end analytics workflow using Python, MySQL, SQL, and Power BI to generate business insights from gaming activity data.

In [41]:
# !/usr/bin/env python3
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine

In [ ]:
# create SQLAlchemy engine to connect to MySQL
engine = create_engine("mysql+pymysql://root:password@localhost:3306/gaming_analytics_db")

## Dataset Scope

This project uses only registration and login activity data.

The A/B testing file was excluded because this project focuses on gaming retention, engagement, DAU, MAU, and cohort analysis.

In [43]:
# read CSV files into pandas DataFrames
df_reg = pd.read_csv('/Users/dineshkumarmuthusamy/Desktop/Gaming Player Retention & Engagement Analytics Platform/data_raw/reg_data.csv', sep=";")
df_auth = pd.read_csv('/Users/dineshkumarmuthusamy/Desktop/Gaming Player Retention & Engagement Analytics Platform/data_raw/auth_data.csv', sep=";")

In [44]:
# Check the structure of the DataFrame
df_reg.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 2 columns):
 #   Column  Non-Null Count    Dtype
---  ------  --------------    -----
 0   reg_ts  1000000 non-null  int64
 1   uid     1000000 non-null  int64
dtypes: int64(2)
memory usage: 15.3 MB

In [45]:
# Check the column names
df_reg.columns.tolist()

['reg_ts', 'uid']

In [46]:
# Check for missing values
df_reg.head()

      reg_ts  uid
0  911382223    1
1  932683089    2
2  947802447    3
3  959523541    4
4  969103313    5

In [47]:
# Check for missing values in the DataFrame
df_reg.isnull().sum()

reg_ts    0
uid       0
dtype: int64

In [48]:
# Check for duplicate rows in the DataFrame
df_reg.duplicated().sum()

np.int64(0)

In [49]:
# Convert 'reg_ts' from Unix timestamp to datetime
df_reg['signup_date'] = pd.to_datetime(df_reg['reg_ts'], unit='s')

In [50]:
# Verify the new column
df_reg[['reg_ts', 'signup_date']].head()

      reg_ts         signup_date
0  911382223 1998-11-18 09:43:43
1  932683089 1999-07-22 22:38:09
2  947802447 2000-01-13 22:27:27
3  959523541 2000-05-28 14:19:01
4  969103313 2000-09-16 11:21:53

## Registration Timestamp Conversion

The reg_ts column was converted from Unix timestamp format into a readable datetime format. This enables registration trend analysis, retention calculations, and cohort analysis.

In [51]:
# Extract the date part from 'signup_date' and create a new column 'signup_day'
df_reg['signup_day'] = df_reg['signup_date'].dt.date

In [52]:

df_reg.to_sql("stg_reg", engine, if_exists="replace", index=False)

1000000

In [53]:
# verify
pd.read_sql("SELECT * FROM stg_reg LIMIT 5;", engine)

      reg_ts  uid         signup_date  signup_day
0  911382223    1 1998-11-18 09:43:43  1998-11-18
1  932683089    2 1999-07-22 22:38:09  1999-07-22
2  947802447    3 2000-01-13 22:27:27  2000-01-13
3  959523541    4 2000-05-28 14:19:01  2000-05-28
4  969103313    5 2000-09-16 11:21:53  2000-09-16

In [54]:
# Check the structure of the DataFrame
df_auth.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9601013 entries, 0 to 9601012
Data columns (total 2 columns):
 #   Column   Dtype
---  ------   -----
 0   auth_ts  int64
 1   uid      int64
dtypes: int64(2)
memory usage: 146.5 MB

In [55]:
# Check for missing values in the DataFrame
df_auth.columns.tolist()

['auth_ts', 'uid']

In [56]:
# Check for duplicate rows in the DataFrame
df_auth.head()

     auth_ts  uid
0  911382223    1
1  932683089    2
2  932921206    2
3  933393015    2
4  933875379    2

In [57]:
# Convert 'auth_ts' from Unix timestamp to datetime
df_auth.isnull().sum()

auth_ts    0
uid        0
dtype: int64

In [58]:
# Check for duplicate rows in the DataFrame
df_auth.duplicated().sum()

np.int64(0)

In [59]:
# Convert 'auth_ts' from Unix timestamp to datetime
df_auth['login_date'] = pd.to_datetime(df_auth['auth_ts'], unit='s')

In [60]:
# Verify the conversion
df_auth[['auth_ts', 'login_date']].head()

     auth_ts          login_date
0  911382223 1998-11-18 09:43:43
1  932683089 1999-07-22 22:38:09
2  932921206 1999-07-25 16:46:46
3  933393015 1999-07-31 03:50:15
4  933875379 1999-08-05 17:49:39

In [61]:
# Extract the date part from 'login_date' and create a new column 'login_day'
df_auth['login_day'] = df_auth['login_date'].dt.date

In [62]:
# Verify the new column
df_auth.to_sql("stg_auth", engine, if_exists="replace", index=False)

9601013

## Load Login Data into MySQL

The cleaned login dataset was loaded into MySQL as a staging table using Pandas and SQLAlchemy. The table serves as the source for gaming analytics metrics such as DAU, MAU, retention, and player engagement analysis.

In [63]:
pd.read_sql("SELECT * FROM stg_auth LIMIT 5;", engine)

     auth_ts  uid          login_date   login_day
0  911382223    1 1998-11-18 09:43:43  1998-11-18
1  932683089    2 1999-07-22 22:38:09  1999-07-22
2  932921206    2 1999-07-25 16:46:46  1999-07-25
3  933393015    2 1999-07-31 03:50:15  1999-07-31
4  933875379    2 1999-08-05 17:49:39  1999-08-05

In [64]:
# Verify the new column
pd.read_sql("SHOW COLUMNS FROM stg_auth;", engine)

        Field      Type Null Key Default Extra
0     auth_ts    bigint  YES        None
1         uid    bigint  YES        None
2  login_date  datetime  YES        None
3   login_day      date  YES        None

In [65]:
# Calculate Daily Active Users (DAU) by counting unique user IDs per day
pd.read_sql("""
SELECT
    login_day,
    COUNT(DISTINCT uid) AS dau
FROM stg_auth
GROUP BY login_day
ORDER BY login_day;
""", engine)

       login_day    dau
0     1998-11-18      1
1     1999-07-22      1
2     1999-07-25      1
3     1999-07-31      1
4     1999-08-05      1
...          ...    ...
6164  2020-09-19  15731
6165  2020-09-20  15829
6166  2020-09-21  15948
6167  2020-09-22  15755
6168  2020-09-23   9526

[6169 rows x 2 columns]

## Daily Active Users (DAU)

Daily Active Users (DAU) measures the number of unique players who logged into the game each day.

DAU is one of the most important gaming analytics KPIs because it helps track player engagement and daily activity trends.

In [66]:
# Calculate Monthly Active Users (MAU) by counting unique user IDs per month
pd.read_sql("""
SELECT
    YEAR(login_date) AS year,
    MONTH(login_date) AS month,
    COUNT(DISTINCT uid) AS mau
FROM stg_auth
GROUP BY YEAR(login_date), MONTH(login_date)
ORDER BY year, month;
""", engine)

     year  month     mau
0    1998     11       1
1    1999      7       1
2    1999      8       1
3    1999      9       1
4    1999     10       1
..    ...    ...     ...
251  2020      5   85978
252  2020      6   89058
253  2020      7   95030
254  2020      8  100036
255  2020      9   91383

[256 rows x 3 columns]

## Monthly Active Users (MAU)

Monthly Active Users (MAU) measures the number of unique players who logged into the game each month.

This KPI helps evaluate long-term user engagement and overall platform activity.

In [67]:
# Calculate new player signups by counting unique user IDs per day
pd.read_sql("""
SELECT
    signup_day,
    COUNT(DISTINCT uid) AS new_players
FROM stg_reg
GROUP BY signup_day
ORDER BY signup_day;
""", engine)

      signup_day  new_players
0     1998-11-18            1
1     1999-07-22            1
2     2000-01-13            1
3     2000-05-28            1
4     2000-09-16            1
...          ...          ...
5105  2020-09-19         1634
5106  2020-09-20         1636
5107  2020-09-21         1638
5108  2020-09-22         1641
5109  2020-09-23         1048

[5110 rows x 2 columns]

## New Player Registrations

New Player Registrations measures the number of unique players who created an account each day.

This KPI helps evaluate user acquisition trends and indicates how effectively the game attracts new players over time.

In [68]:
# Calculate peak DAU by finding the maximum DAU value across all days
pd.read_sql("""
SELECT MAX(dau) AS peak_dau
FROM (
    SELECT
        login_day,
        COUNT(DISTINCT uid) AS dau
    FROM stg_auth
    GROUP BY login_day
) t;
""", engine)

   peak_dau
0     15948

## Peak Daily Active Users

Peak DAU represents the highest number of unique players active on a single day.

This metric helps identify periods of maximum player engagement and platform usage.

In [69]:
# Calculate Day 1 Retention Rate by comparing the number of users who logged in on the day after signup to the total number of new signups
pd.read_sql("""SELECT
    ROUND(
        COUNT(DISTINCT a.uid) * 100.0 /
        COUNT(DISTINCT r.uid), 2
    ) AS day1_retention_rate
FROM stg_reg r
JOIN stg_auth a
    ON r.uid = a.uid
WHERE DATEDIFF(a.login_day, r.signup_day) = 1;""", engine)

   day1_retention_rate
0                100.0

# Day 1 Retention Rate

Day 1 Retention Rate measures the percentage of newly registered players who returned to the game one day after signing up.

Retention is one of the most important gaming analytics KPIs because it indicates player engagement, product stickiness, and the ability of the game to retain new users.

In [70]:
# Calculate Day 7 Retention Rate by comparing the number of users who logged in 7 days after signup to the total number of new signups
pd.read_sql("""
SELECT
    ROUND(
        COUNT(DISTINCT a.uid) * 100.0 /
        COUNT(DISTINCT r.uid), 2
    ) AS day7_retention_rate
FROM stg_reg r
JOIN stg_auth a
    ON r.uid = a.uid
WHERE DATEDIFF(a.login_day, r.signup_day) = 7;
""", engine)

   day7_retention_rate
0                100.0

# Day 7 Retention Rate

Day 7 Retention measures the percentage of players who returned to the game seven days after registration.

This KPI helps evaluate medium-term player engagement and game stickiness.

In [71]:
pd.read_sql("""
SELECT
    ROUND(
        COUNT(DISTINCT a.uid) * 100.0 /
        COUNT(DISTINCT r.uid), 2
    ) AS day30_retention_rate
FROM stg_reg r
JOIN stg_auth a
    ON r.uid = a.uid
WHERE DATEDIFF(a.login_day, r.signup_day) = 30;
""", engine)

   day30_retention_rate
0                 100.0

# Day 30 Retention Rate

Day 30 Retention measures the percentage of players who returned to the game thirty days after registration.

This KPI helps evaluate long-term player retention and overall product health.

In [72]:
# Cohort Analysis: Calculate retention rates for each signup cohort over time
pd.read_sql("""
SELECT
    DATE_FORMAT(r.signup_day, '%%Y-%%m') AS cohort_month,
    DATEDIFF(a.login_day, r.signup_day) AS days_after_signup,
    COUNT(DISTINCT a.uid) AS retained_players
FROM stg_reg r
JOIN stg_auth a
    ON r.uid = a.uid
WHERE DATEDIFF(a.login_day, r.signup_day) >= 0
GROUP BY
    DATE_FORMAT(r.signup_day, '%%Y-%%m'),
    DATEDIFF(a.login_day, r.signup_day)
ORDER BY cohort_month, days_after_signup;
""", engine)

       cohort_month  days_after_signup  retained_players
0           1998-11                  0                 1
1           1999-07                  0                 1
2           1999-07                  3                 1
3           1999-07                  9                 1
4           1999-07                 14                 1
...             ...                ...               ...
294985      2020-09                 18               318
294986      2020-09                 19               257
294987      2020-09                 20               169
294988      2020-09                 21               111
294989      2020-09                 22                25

[294990 rows x 3 columns]

## Cohort Analysis

Cohort Analysis groups players based on their signup period and tracks their retention over time.

This analysis helps identify which player cohorts demonstrate stronger engagement and long-term retention.

## Power BI Reporting Views

SQL views were created to simplify Power BI dashboard development and provide clean reporting tables for player activity and cohort analysis.

In [73]:
# Create a view to combine new player signups and DAU for the gaming dashboard
from sqlalchemy import text

with engine.begin() as conn:
    conn.execute(text("""
        CREATE OR REPLACE VIEW vw_gaming_dashboard AS
        SELECT
            d.activity_day,
            COALESCE(r.new_players, 0) AS new_players,
            COALESCE(a.dau, 0) AS dau
        FROM
        (
            SELECT signup_day AS activity_day
            FROM stg_reg

            UNION

            SELECT login_day AS activity_day
            FROM stg_auth
        ) d
        LEFT JOIN
        (
            SELECT
                signup_day,
                COUNT(DISTINCT uid) AS new_players
            FROM stg_reg
            GROUP BY signup_day
        ) r
        ON d.activity_day = r.signup_day
        LEFT JOIN
        (
            SELECT
                login_day,
                COUNT(DISTINCT uid) AS dau
            FROM stg_auth
            GROUP BY login_day
        ) a
        ON d.activity_day = a.login_day;
    """))

In [74]:
# verify the view
pd.read_sql("SELECT * FROM vw_gaming_dashboard LIMIT 5;", engine)

  activity_day  new_players  dau
0   1998-11-18            1    1
1   1999-07-22            1    1
2   2000-01-13            1    2
3   2000-05-28            1    1
4   2000-09-16            1    1

In [75]:
# Create a view to combine new player signups and DAU for the gaming dashboard
with engine.begin() as conn:
    conn.execute(text("""
        CREATE OR REPLACE VIEW vw_cohort_analysis AS
        SELECT
            DATE_FORMAT(r.signup_day, '%Y-%m') AS cohort_month,
            DATEDIFF(a.login_day, r.signup_day) AS days_after_signup,
            COUNT(DISTINCT a.uid) AS retained_players
        FROM stg_reg r
        JOIN stg_auth a
            ON r.uid = a.uid
        WHERE DATEDIFF(a.login_day, r.signup_day) >= 0
        GROUP BY
            DATE_FORMAT(r.signup_day, '%Y-%m'),
            DATEDIFF(a.login_day, r.signup_day);
    """))

In [76]:
# verify the view
pd.read_sql("SELECT * FROM vw_cohort_analysis LIMIT 5;", engine)

  cohort_month  days_after_signup  retained_players
0      1998-11                  0                 1
1      1999-07                  0                 1
2      1999-07                  3                 1
3      1999-07                  9                 1
4      1999-07                 14                 1

## Conclusion

The analysis shows how registration and login activity data can be used to measure player growth, engagement, and retention.

Key outputs include DAU, MAU, new player registrations, Day 1/7/30 retention, cohort analysis, and Power BI-ready reporting views.

## Power BI Reporting Dataset Preparation

To support dashboard development and business reporting, the final analytical views were extracted from MySQL and loaded into Pandas DataFrames.

Two reporting views were created:

### Gaming Dashboard Reporting View
The `vw_gaming_dashboard` view contains key gaming performance metrics including:

- Daily Active Users (DAU)
- Monthly Active Users (MAU)
- New Player Registrations
- Peak Daily Active Users
- Player Activity Trends

### Cohort Retention Reporting View
The `vw_cohort_analysis` view contains cohort-based retention metrics used to evaluate player engagement and retention behavior over time.

The reporting views were exported as CSV files to create a lightweight and portable dataset for Power BI dashboard development.

### Exported Files

- `vw_gaming_dashboard.csv`
- `vw_cohort_analysis.csv`

These files serve as the final reporting layer used for interactive dashboard creation, KPI monitoring, trend analysis, and cohort retention reporting in Power BI.

### End-to-End Analytics Workflow

**Raw Gaming Data → Data Cleaning & Transformation → MySQL Staging Tables → SQL KPI Analysis → Reporting Views → CSV Export → Power BI Dashboard**

This workflow demonstrates a complete analytics pipeline, transforming raw player activity data into business-ready insights for decision-making and performance monitoring.

In [77]:
# Load the views into pandas DataFrames for analysis and visualization
gaming_dashboard = pd.read_sql("""
SELECT *
FROM vw_gaming_dashboard;
""", engine)

cohort_analysis = pd.read_sql("""
SELECT *
FROM vw_cohort_analysis;
""", engine)

In [78]:
# Export the DataFrames to CSV files for further analysis or visualization
gaming_dashboard.to_csv("vw_gaming_dashboard.csv", index=False)

cohort_analysis.to_csv("vw_cohort_analysis.csv", index=False)